<?php header('Access-Control-Allow-Origin: *') ?>
div
  div#main
    div#logo @title
    div#rightHalf
        div#videoBox_top
        div#videoBox_left
        div#videoBox_right
        div#videoBox_bottom
            div#time
                div#progressBarBG
                    div#progressBar
                div#timeInfo
            div#volume
                div#volumeIcon
                div#volumeBarBG
                    div#volumeBar
                div#volumeInfo
            div#videoControl
                div#rewind
                div#play
                div#stop
                div#pause
                div#forward
            div#status
        div#description_top
        div#description_bottom
        div#description
    div#leftHalf
        div#videoList.style_videoList
            div#video0
            div#video1
            div#video2
            div#video3
            div#video4
            div#videoCount
        div#previous
        div#next
    div#navi
      div#help_navi
        img[src="Images/navi/play.png"]
        img[src="Images/navi/stop.png"]
        img[src="Images/navi/pause.png"]
        img[src="Images/navi/rewind.png"]
        img[src="Images/navi/forward.png"]
        a.style_navi.wide_control_spacing
          "Video Control"
        img[src="Images/navi/enter.png"]
        a.style_navi.wide_control_spacing
          "Full-screen/Window mode"
        img[src="Images/navi/return.png"]
        a.style_navi
          "Return"
